service: hridoy-aws-appsync-enlear
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs16.x
  lamdaHashingVersion: 20201221
  region: us-east-1
  stage: dev

resources:
  Resources:
    ${file(resources.yml)}
